In [2]:
import pandas as pd

In [3]:
data = [1,2,3,4,5]
series = pd.Series(data)

In [4]:
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
#Create a series from dictionary
data = {"a":1,"b":2,"c":3,"d":4,"e":5}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
data = [10,20,30]
index = ["a","b","c"]
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

DataFrame

Create a dataframe from a dictionary of list

In [7]:
data = {
    "Name":["Krish", "John","Jack"],
    "Age":[10,20,30],
    "City": ["Bangalore","New York", "Florida"]
}

In [8]:
df = pd.DataFrame(data)

In [9]:
df

    Name  Age       City
0  Krish   10  Bangalore
1   John   20   New York
2   Jack   30    Florida

In [10]:
data = [
    {"Name": "Apurba", "Age": 20, "City": "Kolkata"},
    {"Name": "Aharsh", "Age": 20, "City": "Bangalore"},
]

In [11]:
df = pd.DataFrame(data)
print(df)

     Name  Age       City
0  Apurba   20    Kolkata
1  Aharsh   20  Bangalore

From csv file

In [13]:
df = pd.read_csv("sales_data.csv")

In [14]:
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [15]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

Accesing data from dataframe

In [17]:
df["Transaction ID"]

0      10001
1      10002
2      10003
3      10004
4      10005
       ...
235    10236
236    10237
237    10238
238    10239
239    10240
Name: Transaction ID, Length: 240, dtype: int64

In [23]:
data = [
    {"Name": "Apurba", "Age": 20, "City": "Kolkata"},
    {"Name": "Aharsh", "Age": 30, "City": "Bangalore"},
]

In [24]:
df = pd.DataFrame(data)

In [25]:
df

     Name  Age       City
0  Apurba   20    Kolkata
1  Aharsh   30  Bangalore

In [26]:
df.at[1, "Age"]

np.int64(30)

iat - both row index and column index

In [27]:
df.iat[1,1]

np.int64(30)

Data Manipulation with data frames

In [28]:
df

     Name  Age       City
0  Apurba   20    Kolkata
1  Aharsh   30  Bangalore

In [31]:
df["Salary"] = ["50000", "600000"] #adding a column

In [32]:
df

     Name  Age       City  Salary
0  Apurba   20    Kolkata   50000
1  Aharsh   30  Bangalore  600000

In [35]:
df.drop("Salary", axis=1,inplace=True)

In [36]:
df

     Name  Age       City
0  Apurba   20    Kolkata
1  Aharsh   30  Bangalore

In [38]:
df["Age"] = df["Age"]+1

In [39]:
df

     Name  Age       City
0  Apurba   21    Kolkata
1  Aharsh   31  Bangalore