In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("sales_data.csv")

In [7]:
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [8]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [9]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     239.000000
mean      10120.50000    2.158333   236.395583     336.894812
std          69.42622    1.322454   429.446695     486.470128
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      64.455000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.450000
max       10240.00000   10.000000  3899.990000    3899.990000

In [10]:
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

Handling missing values

In [11]:
df.isnull()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
235,False,False,False,False,False,False,False,False,False
236,False,False,False,False,False,False,False,False,False
237,False,False,False,False,False,False,False,False,False
238,False,False,False,False,False,False,False,False,False
239,False,False,False,False,False,False,False,False,False

In [12]:
df.isnull().any(axis=1) #axis = 1 checks the row-wise for missing values

0      False
1      False
2      False
3      False
4      False
       ...
235    False
236    False
237    False
238    False
239    False
Length: 240, dtype: bool

In [13]:
df.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       1
Region              0
Payment Method      0
dtype: int64

In [14]:
df_filled = df.fillna(0)

In [15]:
##Filling missing values with mean of the column

In [16]:
df["Total_Revenue_fillNA"] = df["Total Revenue"].fillna(df["Total Revenue"].mean())

In [17]:
df["Total_Revenue_fillNA"]

0      1999.98
1       499.99
2       209.97
3        63.96
4        89.99
        ...
235     159.99
236     270.00
237      32.97
238      55.00
239      59.98
Name: Total_Revenue_fillNA, Length: 240, dtype: float64

In [18]:
df.dtypes

Transaction ID            int64
Date                     object
Product Category         object
Product Name             object
Units Sold                int64
Unit Price              float64
Total Revenue           float64
Region                   object
Payment Method           object
Total_Revenue_fillNA    float64
dtype: object

In [19]:
df.rename(columns={'Date':'Sale Date'}, inplace=True)

In [20]:
df.head(5)

,Transaction ID,Sale Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_fillNA
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99

In [21]:
#change datatypes
df["Units Sold New"]=df["Units Sold"].fillna(df["Units Sold"].mean()).astype(float)

In [22]:
df.head(5)

,Transaction ID,Sale Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_fillNA,Units Sold New
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,2.0
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,1.0
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,3.0
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,4.0
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,1.0

In [23]:
df["Correct Units Sold"] = df["Units Sold"].apply(lambda x:x*2)

In [33]:
df.head(10)

,Transaction ID,Sale Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_fillNA,Units Sold New,Correct Units Sold
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,2.0,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,1.0,2
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,3.0,6
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,4.0,8
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,1.0,2
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card,149.95,5.0,10
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card,2499.99,1.0,2
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal,1199.98,2.0,4
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card,539.94,6.0,12
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card,51.98,2.0,4

In [25]:
#Data Aggregating and Grouping
group_mean = df.groupby(["Product Category"])["Units Sold"].mean()

In [26]:
group_mean

Product Category
Beauty Products    1.150
Books              2.850
Clothing           3.625
Electronics        1.650
Home Appliances    1.475
Sports             2.200
Name: Units Sold, dtype: float64

In [31]:
#aggregate multiple functions
group_agg = df.groupby(["Product Category"])["Units Sold"].agg("mean", "sum", "count")

In [32]:
group_agg

Product Category
Beauty Products    1.150
Books              2.850
Clothing           3.625
Electronics        1.650
Home Appliances    1.475
Sports             2.200
Name: Units Sold, dtype: float64

In [35]:
###Merging and joining dataframes

df1 = pd.DataFrame({"Key":["A","B","C"], "value1":[1,2,3]})
df2 = pd.DataFrame({"Key":["A","B","D"], "value2":[4,5,6]})

In [38]:
df1

  Key  value1
0   A       1
1   B       2
2   C       3

In [40]:
df2

  Key  value2
0   A       4
1   B       5
2   D       6

In [41]:
pd.merge(df1,df2, on="Key", how="inner")

  Key  value1  value2
0   A       1       4
1   B       2       5

In [42]:
pd.merge(df1,df2, on="Key",how="outer")

  Key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [43]:
pd.merge(df1,df2,on="Key",how="left")

  Key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [44]:
pd.merge(df1,df2,on="Key",how="right")

  Key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6